name: Zip Files
on: [push]
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
      - uses: actions/upload-artifact@v1  
        with:
          files: manifest.json
          dest: result.zip
          name: my-artifact
          path: ${{ github.workspace }}/result.zip  
 
    
